name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.100

      - name: Install Tools
        run: dotnet tool restore

      - name: Build
        run: dotnet run Publish

      - name: Publish App
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: publish/app